from sqlalchemy import text

from database import engine


def init_project_task_activity_daily() -> None:
    with engine.begin() as connection:
        connection.execute(text("""
            CREATE TABLE IF NOT EXISTS project_task_activity_daily (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL
                    REFERENCES projects(project_id) ON DELETE CASCADE,
                date DATE NOT NULL,
                open_tasks INTEGER NOT NULL DEFAULT 0 CHECK (open_tasks >= 0),
                completed_tasks INTEGER NOT NULL DEFAULT 0
                    CHECK (completed_tasks >= 0),
                CONSTRAINT uq_project_task_activity_daily_project_date
                    UNIQUE (project_id, date)
            )
        """))
        connection.execute(text("""
            INSERT INTO project_task_activity_daily (
                project_id,
                date,
                open_tasks,
                completed_tasks
            )
            SELECT
                project.project_id,
                (NOW() AT TIME ZONE 'UTC')::date,
                COUNT(task.id) FILTER (WHERE task.status <> 'DONE'),
                COUNT(task.id) FILTER (WHERE task.status = 'DONE')
            FROM projects AS project
            LEFT JOIN teams AS team
                ON team.project_id = project.project_id
            LEFT JOIN tasks AS task
                ON task.team_id = team.team_id
            GROUP BY project.project_id
            ON CONFLICT (project_id, date) DO NOTHING
        """))
